%LET YEAR=07;
%LET SOURCE=/folders/myshortcuts/DATA/ACS/20&YEAR./1YR/;

LIBNAME ACS&YEAR. "&SOURCE.";

FILENAME H SASZIPAM "&SOURCE.csv_hus.zip";
FILENAME P SASZIPAM "&SOURCE.csv_pus.zip";

DATA HTEXT;
	INFILE H(ss&YEAR.husa.csv) LRECL=2000 OBS=1 TRUNCOVER;
	INPUT TEXT $2000.;
RUN;

DATA PTEXT;
	INFILE P(ss&YEAR.pusa.csv) LRECL=2000 OBS=1 TRUNCOVER;
	INPUT TEXT $2000.;
RUN;

DATA PART1;
	INFILE P(ss&YEAR.pusa.csv)
		FIRSTOBS=2
 		DSD DLM='2C0D'x
		LRECL=2000 MISSOVER ;
	%INCLUDE "&SOURCE.P_LENGTH.TXT";
	%INCLUDE "&SOURCE.P_INPUT.TXT";
	%INCLUDE "&SOURCE.P_LABEL.TXT";
RUN;

DATA PART2;
	INFILE P(ss&YEAR.pusb.csv)
		FIRSTOBS=2
 		DSD DLM='2C0D'x
		LRECL=2000 MISSOVER ;
	%INCLUDE "&SOURCE.P_LENGTH.TXT";
	%INCLUDE "&SOURCE.P_INPUT.TXT";
	%INCLUDE "&SOURCE.P_LABEL.TXT";
RUN;

DATA ACS&YEAR..P;
	SET PART1 PART2;
RUN;

DATA HART1;
	INFILE H(ss&YEAR.husa.csv)
		FIRSTOBS=2
 		DSD DLM='2C0D'x
		LRECL=2000 MISSOVER ;
	%INCLUDE "&SOURCE.H_LENGTH.TXT";
	%INCLUDE "&SOURCE.H_INPUT.TXT";
	%INCLUDE "&SOURCE.H_LABEL.TXT";
RUN;

DATA HART2;
	INFILE H(ss&YEAR.husb.csv)
		FIRSTOBS=2
 		DSD DLM='2C0D'x
		LRECL=2000 MISSOVER ;
	%INCLUDE "&SOURCE.H_LENGTH.TXT";
	%INCLUDE "&SOURCE.H_INPUT.TXT";
	%INCLUDE "&SOURCE.H_LABEL.TXT";
RUN;

DATA ACS&YEAR..H;
	SET HART1 HART2;
RUN;
