attrib  hrhhid       length=$15   label="Household-identifier,scrambled";  
attrib  hrmonth      length=3     label="Household-month of interview";    
attrib  hryear4      length=4     label="Household-4 digit year of interview";  
attrib  hurespli     length=3     label="Household-line number of current respo";  
attrib  hufinal      length=3     label="Household-final code,status of intervi";  
attrib  huspnish     length=3     label="Household-spanish only spoken";   
attrib  hetenure     length=3     label="Household-own/rent living quarters";  
attrib  hehousut     length=3     label="Household-type of living quarters";  
attrib  hetelhhd     length=3     label="Household-phone in living quarters,y/n";  
attrib  hetelavl     length=3     label="Household-no residential phone,availab";  
attrib  hephoneo     length=3     label="Household-phone interview acceptable,y";  
attrib  hufaminc     length=3     label="Household-total family income in past ";  
attrib  hutypea      length=3     label="Household-type A non-interview categor";  
attrib  hutypb       length=3     label="Household-type B non-interview categor";  
attrib  hutypc       length=3     label="Household-type C non-interview categor";  
attrib  hwhhwgt      length=8     label="Weight-household";                
attrib  hrintsta     length=3     label="Household-interview/non-interview stat";  
attrib  hrnumhou     length=3     label="Household-total # of members";    
attrib  hrhtype      length=3     label="Household-type of family/single indivi";  
attrib  hrmis        length=3     label="Household-month-in-sample";       
attrib  huinttyp     length=3     label="Household-type of";               
attrib  huprscnt     length=3     label="Household-# of actual & attempted pers";  
attrib  hrlonglk     length=3     label="Household-longitudinal link indicator";  
attrib  hrsample     length=$4    label="Household-sample ID (Created in reform";  
attrib  hrsersuf     length=$3    label="Household-serial suffix";         
attrib  huhhnum      length=3     label="Household-replacement number";    
attrib  hubus        length=3     label="Labor Force-presence of business/farm ";  
attrib  hubusl1      length=3     label="Labor Force-line numbers of business/f";  
attrib  hubusl2      length=3     label="Labor Force-line numbers of business/f";  
attrib  hubusl3      length=3     label="Labor Force-line numbers of business/f";  
attrib  hubusl4      length=3     label="Labor Force-line numbers of business/f";  
attrib  gereg        length=3     label="Geography-region";                
attrib  gestcen      length=3     label="Geography-census state code";     
attrib  gestfips     length=3     label="Geography-FIPS state code";       
attrib  gecmsa       length=3     label="Geography-consolidated MSA code";  
attrib  gemsa        length=4     label="Geography-MSA code";              
attrib  geco         length=3     label="Geography-FIPS county code";      
attrib  gemsast      length=3     label="Geography-MSA/central city status";  
attrib  gemetsta     length=3     label="Geography-metropolitan status";   
attrib  geindvcc     length=3     label="Geography-individual central city code";  
attrib  gemsasz      length=3     label="Geography-MSA/PMSA size";         
attrib  gecmsasz     length=3     label="Geography-CMSA/MSA size";         
attrib  hulensec     length=4     label="Household-total time(seconds) to compl";  
attrib  proldrrp     length=3     label="Demographics-recode to collapse new RR";  
attrib  pupelig      length=3     label="Demographics-interview status of perso";  
attrib  perrp        length=3     label="Demographics-relationship to reference";  
attrib  peparent     length=3     label="Demographics-parent line number";  
attrib  peage        length=3     label="Demographics-age top coded at 90 years";  
attrib  ptage        length=3     label="Demographics-top coded flag for age";  
attrib  pemaritl     length=3     label="Demographics-marital status";     
attrib  pespouse     length=3     label="Demographics-spouse line number";  
attrib  pesex        length=3     label="Demographics-sex";                
attrib  puafever     length=3     label="Demographics-ever did military service";  
attrib  peafwhen     length=3     label="Demographics-past military service,per";  
attrib  peafnow      length=3     label="Demographics-currently in armed forces";  
attrib  peeduca      length=3     label="Demographics-highest level of school";  
attrib  perace       length=3     label="Demographics-race of respondent";  
attrib  prorigin     length=3     label="Demographics-hispanic origin or descen";  
attrib  puchinhh     length=3     label="Demographics-reason for the changes in";  
attrib  purelflg     length=3     label="Demographics-flag for persons related ";  
attrib  pulineno     length=3     label="Demographics-line number";        
attrib  prfamnum     length=3     label="Demographics-family number";      
attrib  prfamrel     length=3     label="Demographics-family relationship(recod";  
attrib  prfamtyp     length=3     label="Demographics-family type(recode)";  
attrib  prhspnon     length=3     label="Demographics-hispanic/non-hispanic ori";  
attrib  prmarsta     length=3     label="Demographics-marital status(recode)";  
attrib  prpertyp     length=3     label="Demographics-person type(recode)";  
attrib  penatvty     length=3     label="Demographics-native country of sample ";  
attrib  pemntvty     length=3     label="Demographics-native country of mother";  
attrib  pefntvty     length=3     label="Demographics-native country of father";  
attrib  prcitshp     length=3     label="Demographics-United States citizenship";  
attrib  prcitflg     length=3     label="Demographics-citizenship allocation fl";  
attrib  prinusyr     length=3     label="Demographics-immigrant's year of entry";  
attrib  puslfprx     length=3     label="Labor Force-information given by self/";  
attrib  pemlr        length=3     label="Labor Force-employment status";   
attrib  puwk         length=3     label="Labor Force-did work for pay/profit";  
attrib  pubus1       length=3     label="Labor Force-unpaid work in family";  
attrib  pubus2ot     length=3     label="Labor Force-stores BUS2 entry";   
attrib  pubusck1     length=3     label="Labor Force-filter for question on unp";  
attrib  pubusck2     length=3     label="Labor Force-(family business)skips own";  
attrib  pubusck3     length=3     label="Labor Force-filter for business owners";  
attrib  pubusck4     length=3     label="Labor Force-filter for business owners";  
attrib  puretot      length=3     label="Labor Force-verify retirement";   
attrib  pudis        length=3     label="Labor Force-verify disability status f";  
attrib  peret1       length=3     label="Labor Force-(retired)want full/part-ti";  
attrib  pudis1       length=3     label="Labor Force-probe #1 for disability";  
attrib  pudis2       length=3     label="Labor Force-probe #2 for disability";  
attrib  puabsot      length=3     label="Labor Force-output var determines abse";  
attrib  pulay        length=3     label="Labor Force-person on layoff from job";  
attrib  peabsrsn     length=3     label="Labor Force-reason for work absence la";  
attrib  peabspdo     length=3     label="Labor Force-paid absence from work,y/n";  
attrib  pemjot       length=3     label="Labor Force-had multiple jobs,y/n";  
attrib  pemjnum      length=3     label="Labor Force-# of jobs had";       
attrib  pehrusl1     length=3     label="Labor Force-# hours usually worked at ";  
attrib  pehrusl2     length=3     label="Labor Force-# hours usually worked at ";  
attrib  pehrftpt     length=3     label="Labor Force-usually work full-time,y/n";  
attrib  pehruslt     length=3     label="Labor Force-# hours usually worked at ";  
attrib  pehrwant     length=3     label="Labor Force-full-time work desired,y/n";  
attrib  pehrrsn1     length=3     label="Labor Force-(part-timer)reason";  
attrib  pehrrsn2     length=3     label="Labor Force-(part-timer)reason not ful";  
attrib  pehrrsn3     length=3     label="Labor Force-(full-timer)reason part-ti";  
attrib  puhroff1     length=3     label="Labor Force-any work hours were lost l";  
attrib  puhroff2     length=3     label="Labor Force-number of work hours lost ";  
attrib  puhrot1      length=3     label="Labor Force-extra hours worked last we";  
attrib  puhrot2      length=3     label="Labor Force-number of extra hours work";  
attrib  pehract1     length=3     label="Labor Force-# hours actually worked at";  
attrib  pehract2     length=3     label="Labor Force-# hours actually worked at";  
attrib  pehractt     length=3     label="Labor Force-# hours actually worked at";  
attrib  pehravl      length=3     label="Labor Force-(part-timer)available for";  
attrib  pulbhsec     length=4     label="Labor Force-total seconds to complete ";  
attrib  puhrck1      length=3     label="Labor Force-remove groups from actual ";  
attrib  puhrck2      length=3     label="Labor Force-skips persons out of PT se";  
attrib  puhrck3      length=3     label="Labor Force-skips persons out of PT se";  
attrib  puhrck4      length=3     label="Labor Force-skips persons";       
attrib  puhrck5      length=3     label="Labor Force-filter for multiple jobhol";  
attrib  puhrck6      length=3     label="Labor Force-filter for actual hours jo";  
attrib  puhrck7      length=3     label="Labor Force-filter for hours worked pa";  
attrib  puhrck12     length=3     label="Labor Force-filter for <15 hours to go";  
attrib  pulaydt      length=3     label="Labor Force-person on layoff,has retur";  
attrib  pulay6m      length=3     label="Labor Force-person on layoff,recalled ";  
attrib  pelayavl     length=3     label="Labor Force-(layoff)available for work";  
attrib  pulayavr     length=3     label="Labor Force-person on layoff,reason";  
attrib  pelaylk      length=3     label="Labor Force-(layoff)called back,still";  
attrib  pelaydur     length=3     label="Labor Force-(layoff)# weeks looking fo";  
attrib  pelayfto     length=3     label="Labor Force-(layoff)from full-time job";  
attrib  pulayck1     length=3     label="Labor Force-filter for previous month ";  
attrib  pulayck2     length=3     label="Labor Force-filter/plug for dependent ";  
attrib  pulayck3     length=3     label="Labor Force-dependent I & O filter/car";  
attrib  pulk         length=3     label="Labor Force-looked for work in last 4 ";  
attrib  pelkm1       length=3     label="Labor Force-(unemployed)looking-search";  
attrib  pulkm2       length=3     label="Labor Force-(job search)methods,all in";  
attrib  pulkm3       length=3     label="Labor Force-(job search)methods-follow";  
attrib  pulkm4       length=3     label="Labor Force-(job search)methods-follow";  
attrib  pulkm5       length=3     label="Labor Force-(job search)methods follow";  
attrib  pulkm6       length=3     label="Labor Force-(job search)methods follow";  
attrib  pulkdk1      length=3     label="Labor Force-(unemployed) followup to L";  
attrib  pulkdk2      length=3     label="Labor Force-(looking for work)followup";  
attrib  pulkdk3      length=3     label="Labor Force-(looking for work)followup";  
attrib  pulkdk4      length=3     label="Labor Force-(looking for work)followup";  
attrib  pulkdk5      length=3     label="Labor Force-(looking for work)followup";  
attrib  pulkdk6      length=3     label="Labor Force-(looking for work)followup";  
attrib  pulkps1      length=3     label="Labor Force-(job search)passive entry ";  
attrib  pulkps2      length=3     label="Labor Force-(job search)passive entry ";  
attrib  pulkps3      length=3     label="Labor Force-(job search)passive entry ";  
attrib  pulkps4      length=3     label="Labor Force-(job search)passive entry ";  
attrib  pulkps5      length=3     label="Labor Force-(job search)passive entry ";  
attrib  pulkps6      length=3     label="Labor Force-(job search)passive entry ";  
attrib  pelkavl      length=3     label="Labor Force-(unemployed)available for ";  
attrib  pulkavr      length=3     label="Labor Force-reason jobseeker unavailab";  
attrib  pelkll1o     length=3     label="Labor Force-(unemployed)looking-activi";  
attrib  pelkll2o     length=3     label="Labor Force-(unemployed)looking-lost/q";  
attrib  pelklwo      length=3     label="Labor Force-(unemployed)looking-when l";  
attrib  pelkdur      length=3     label="Labor Force-(unemployed)#weeks on job ";  
attrib  pelkfto      length=3     label="Labor Force-(unemployed)looking-full-t";  
attrib  pedwwnto     length=3     label="Labor Force-(not in,discouraged)wanted";  
attrib  pedwrsn      length=3     label="Labor Force-(not in,discouraged)reason";  
attrib  pedwlko      length=3     label="Labor Force-(not in,discouraged)look f";  
attrib  pedwwk       length=3     label="Labor Force-(not in,discouraged)worked";  
attrib  pedw4wk      length=3     label="Labor Force-(not in,discouraged)worked";  
attrib  pedwlkwk     length=3     label="Labor Force-(not in,discouraged)looked";  
attrib  pedwavl      length=3     label="Labor Force-(not in,discouraged)availa";  
attrib  pedwavr      length=3     label="Labor Force-(not in,discouraged)reason";  
attrib  pudwck1      length=3     label="Labor Force-filter for discouraged wor";  
attrib  pudwck2      length=3     label="Labor Force-filter for disabled";  
attrib  pudwck3      length=3     label="Labor Force-filter for retired";  
attrib  pudwck4      length=3     label="Labor Force-filter/plug for passive";  
attrib  pudwck5      length=3     label="Labor Force-filter/plug for passive";  
attrib  pejhwko      length=3     label="Labor Force-(not in,job history)worked";  
attrib  pujhdp1o     length=3     label="Labor Force-out variable for JHDP1";  
attrib  pejhrsn      length=3     label="Labor Force-(not in,job history)reason";  
attrib  pejhwant     length=3     label="Labor Force-(not in,job history)look f";  
attrib  pujhck1      length=3     label="Labor Force-filter for outgoing rotati";  
attrib  pujhck2      length=3     label="Labor Force-filter for persons going t";  
attrib  prabsrea     length=3     label="Labor Force-work absence,reason & pay ";  
attrib  prcivlf      length=3     label="Labor Force-part of/not part of";  
attrib  prdisc       length=3     label="Labor Force-discouraged worker/conditi";  
attrib  premphrs     length=3     label="Labor Force-reason for work absence or";  
attrib  prempnot     length=3     label="Labor Force-employment status,recode";  
attrib  prexplf      length=3     label="Labor Force-employed/unemployed";  
attrib  prftlf       length=3     label="Labor Force-full-time/part-time";  
attrib  prhrusl      length=3     label="Labor Force-hours usually worked weekl";  
attrib  prjobsea     length=3     label="Labor Force-job search,recode";   
attrib  prpthrs      length=3     label="Labor";                           
attrib  prptrea      length=3     label="Labor Force-(part-timer)specific reaso";  
attrib  prunedur     length=3     label="Labor Force-unemployment duration";  
attrib  prusftpt     length=3     label="Labor Force-full-time/part-time/status";  
attrib  pruntype     length=3     label="Labor Force-unemployment reason";  
attrib  prwksch      length=3     label="Labor Force-employment status by time";  
attrib  prwkstat     length=3     label="Labor Force-full-time/part-time work s";  
attrib  prwntjob     length=3     label="Labor Force-(not in)or wants job-recod";  
attrib  pujhck3      length=3     label="Labor Force-filter for unemployed job";  
attrib  pujhck4      length=3     label="Labor Force-(not in)filter for depende";  
attrib  pujhck5      length=3     label="Labor Force-(not in)filter/carryover f";  
attrib  puiodp1      length=3     label="Indus.& Occ.-verification of previous ";  
attrib  puiodp2      length=3     label="Indus.& Occ.-job duties changed since ";  
attrib  puiodp3      length=3     label="Indus.& Occ.-verify previous month's";  
attrib  peio1cow     length=3     label="Indus.& Occ.-(main job)class of worker";  
attrib  puio1mfg     length=3     label="Indus.& Occ.-(main job)in";       
attrib  peio1icd     length=3     label="Indus.& Occ.-(main job)industry code";  
attrib  peio1ocd     length=3     label="Indus.& Occ.-(main job)occupation code";  
attrib  peio2cow     length=3     label="Indus.& Occ.-(second job)class of work";  
attrib  puio2mfg     length=3     label="Indus.& Occ.-(second job)in";     
attrib  peio2icd     length=3     label="Indus.& Occ.-(second job)industry code";  
attrib  peio2ocd     length=3     label="Indus.& Occ.-(second job)occupation co";  
attrib  puiock1      length=3     label="Indus.& Occ.-filter for dependent indu";  
attrib  puiock2      length=3     label="Indus.& Occ.-filter for previous month";  
attrib  puiock3      length=3     label="Indus.& Occ.-filter for previous month";  
attrib  prioelg      length=3     label="Labor Force-industry and occupation ed";  
attrib  pragna       length=3     label="Indus.& Occ.-industry,agriculture/non-";  
attrib  prcow1       length=3     label="Indus.& Occ.-(main job)class of worker";  
attrib  prcow2       length=3     label="Indus.& Occ.-(second job)class of";  
attrib  prcowpg      length=3     label="Indus.& Occ.-(main job)class of";  
attrib  prdtcow1     length=3     label="Indus.& Occ.-(main job)detailed class ";  
attrib  prdtcow2     length=3     label="Indus.& Occ.-(second job)detailed clas";  
attrib  prdtind1     length=3     label="Indus.& Occ.-(main job)detailed indust";  
attrib  prdtind2     length=3     label="Indus.& Occ.-(second job)detailed";  
attrib  prdtocc1     length=3     label="Indus.& Occ.-(main job)detailed occupa";  
attrib  prdtocc2     length=3     label="Indus.& Occ.-(second job)detailed occu";  
attrib  premp        length=3     label="Labor Force-employed non-farm/non-priv";  
attrib  prmjind1     length=3     label="Indus.& Occ.-(main job)industry,major ";  
attrib  prmjind2     length=3     label="Indus.& Occ.-(second job)industry,majo";  
attrib  prmjocc1     length=3     label="Indus.& Occ.-(main job)occupation,majo";  
attrib  prmjocc2     length=3     label="Indus.& Occ.-(second job)occupation,ma";  
attrib  prmjocgr     length=3     label="Indus.& Occ.-(main job)occupation,4 gr";  
attrib  prnagpws     length=3     label="Indus.& Occ.-non-agriculture/private/s";  
attrib  prnagws      length=3     label="Indus.& Occ.-non-agriculture/salary wo";  
attrib  prsjmj       length=3     label="Indus.& Occ.-single/multiple jobholder";  
attrib  prerelg      length=3     label="Demographics-earnings edit eligibility";  
attrib  peernuot     length=3     label="Earnings-overtime pay/tips/commission,";  
attrib  peernper     length=3     label="Earnings-when received,periodicity";  
attrib  peernrt      length=3     label="Earnings-paid hourly,y/n";        
attrib  peernhry     length=3     label="Earnings-hourly/non-hourly worker";  
attrib  puernh1c     length=8     label="Earnings-hourly pay rate,excluding ove";  
attrib  peernh2      length=8     label="Earnings-(main job)hourly pay rate,amo";  
attrib  peernh1o     length=8     label="Earnings-hourly pay rate,amount";  
attrib  prernhly     length=8     label="Earnings-hourly pay rate,amount-recode";  
attrib  pthr         length=3     label="Earnings-hourly pay-Top Code";    
attrib  peernhro     length=3     label="Earnings-#hours usually worked";  
attrib  prernwa      length=8     label="Earnings-weekly earnings,amount-recode";  
attrib  ptwk         length=3     label="Earnings-weekly-top code flag";   
attrib  peern        length=8     label="Earnings-(weekly)amount of overtime ea";  
attrib  puern2       length=8     label="Earnings-(calculated)weekly overtime";  
attrib  ptot         length=3     label="Earnings-weekly overtime,amount-top co";  
attrib  peernwkp     length=3     label="Earnings-#paid weeks per year";   
attrib  peernlab     length=3     label="Earnings-union member,y/n";       
attrib  peerncov     length=3     label="Earnings-covered by labor union/employ";  
attrib  penlfjh      length=3     label="Labor Force-(not in)last worked at";  
attrib  penlfret     length=3     label="Labor Force-(retired) from job/busines";  
attrib  penlfact     length=3     label="Labor Force-(not in)reason";      
attrib  punlfck1     length=3     label="Labor Force-age filter for retirement";  
attrib  punlfck2     length=3     label="Labor Force-outgoing rotation filter";  
attrib  peschenr     length=3     label="School Enrollment-in high";       
attrib  peschft      length=3     label="School Enrollment-full-time/part-time";  
attrib  peschlvl     length=3     label="School Enrollment-in high";       
attrib  prnlfsch     length=3     label="School Enrollment-(not in labor";  
attrib  pwfmwgt      length=8     label="Weight-family";                   
attrib  pwlgwgt      length=8     label="Weight-longitudinal weight";      
attrib  pworwgt      length=8     label="Weight-outgoing rotation weight";  
attrib  pwsswgt      length=8     label="Weight-second stage weight (rake 6 fin";  
attrib  pwvetwgt     length=8     label="Weight-veterans weight";          
attrib  prchld       length=3     label="Presence of own children <18 years of age (Starts Nov 1999)";  
attrib  prnmchld     length=3     label="Number of own children <18 years of age (Starts Nov 1999) ";  
attrib  prwernal     length=3     label="Earnings-(person)weekly earnings alloc";  
attrib  prhernal     length=3     label="Earnings-persons hourly earnings recod";  
attrib  hxtenure     length=3     label="Household-allocation flag for HETENURE";  
attrib  hxhousut     length=3     label="Household-allocation flag for HEHOUSUT";  
attrib  hxtelhhd     length=3     label="Household-allocation flag for HETELHHD";  
attrib  hxtelavl     length=3     label="Household-allocation flag for HETELAVL";  
attrib  hxphoneo     length=3     label="Household-allocation flag for HEPHONEO";  
attrib  pxinusyr     length=3     label="Demographics-allocation flag for PEINU";  
attrib  pxrrp        length=3     label="Demographics-allocation flag for PERRP";  
attrib  pxparent     length=3     label="Demographics-allocation flag for PEPAR";  
attrib  pxage        length=3     label="Demographics-allocation flag for PEAGE";  
attrib  pxmaritl     length=3     label="Demographics-allocation flag for PEMAR";  
attrib  pxspouse     length=3     label="Demographics-allocation flag for PESPO";  
attrib  pxsex        length=3     label="Demographics-allocation flag for PESEX";  
attrib  pxafwhen     length=3     label="Demographics-allocation flag for PEAFW";  
attrib  pxafnow      length=3     label="Demographics-allocation flag for PEAFN";  
attrib  pxeduca      length=3     label="Demographics-allocation flag for PEEDU";  
attrib  pxrace       length=3     label="Demographics-allocation flag for PERAC";  
attrib  pxnatvty     length=3     label="Demographics-allocation flag for PENAT";  
attrib  pxmntvty     length=3     label="Demographics-allocation flag for PEMNT";  
attrib  pxfntvty     length=3     label="Demographics-allocation flag for PEFNT";  
attrib  pxorigin     length=3     label="Demographics-allocation flag for PEORI";  
attrib  pxmlr        length=3     label="Labor Force-allocation flag for PEMLR";  
attrib  pxret1       length=3     label="Labor Force-allocation flag for PERET1";  
attrib  pxabsrsn     length=3     label="Labor Force-allocation flag for PEABSR";  
attrib  pxabspdo     length=3     label="Labor Force-allocation flag for PEABSP";  
attrib  pxmjot       length=3     label="Labor Force-allocation flag for PEMJOT";  
attrib  pxmjnum      length=3     label="Labor Force-allocation flag for PEMJNU";  
attrib  pxhrusl1     length=3     label="Labor Force-allocation flag for PEHRUS";  
attrib  pxhrusl2     length=3     label="Labor Force-allocation flag for PEHRUS";  
attrib  pxhrftpt     length=3     label="Labor Force-allocation flag for PEHRFT";  
attrib  pxhruslt     length=3     label="Labor Force-allocation flag for PEHRUS";  
attrib  pxhrwant     length=3     label="Labor Force-allocation flag for PEHRWA";  
attrib  pxhrrsn1     length=3     label="Labor Force-allocation flag for PEHRRS";  
attrib  pxhrrsn2     length=3     label="Labor Force-allocation flag for PEHRRS";  
attrib  pxhract1     length=3     label="Labor Force-allocation flag for PEHRAC";  
attrib  pxhract2     length=3     label="Labor Force-allocation flag for PEHRAC";  
attrib  pxhractt     length=3     label="Labor Force-allocation flag for PEHRAC";  
attrib  pxhrrsn3     length=3     label="Labor Force-allocation flag for PEHRRS";  
attrib  pxhravl      length=3     label="Labor Force-allocation flag for PEHRAV";  
attrib  pxlayavl     length=3     label="Labor Force-allocation flag for PELAYA";  
attrib  pxlaylk      length=3     label="Labor Force-allocation flag for PELAYL";  
attrib  pxlaydur     length=3     label="Labor Force-allocation flag for PELAYD";  
attrib  pxlayfto     length=3     label="Labor Force-allocation flag for PELAYF";  
attrib  pxlkm1       length=3     label="Labor Force-allocation flag for PELKM1";  
attrib  pxlkavl      length=3     label="Labor Force-allocation flag for PELKAV";  
attrib  pxlkll1o     length=3     label="Labor Force-allocation flag for PELKLL";  
attrib  pxlkll2o     length=3     label="Labor Force-allocation flag for PELKLL";  
attrib  pxlklwo      length=3     label="Labor Force-allocation flag for PELKLW";  
attrib  pxlkdur      length=3     label="Labor Force-allocation flag for PELKDU";  
attrib  pxlkfto      length=3     label="Labor Force-allocation flag for PELKFT";  
attrib  pxdwwnto     length=3     label="Labor Force-allocation flag for PEDWWN";  
attrib  pxdwrsn      length=3     label="Labor Force-allocation flag for PEDWRS";  
attrib  pxdwlko      length=3     label="Labor Force-allocation flag for PEDWLK";  
attrib  pxdwwk       length=3     label="Labor Force-allocation flag for PEDWWK";  
attrib  pxdw4wk      length=3     label="Labor Force-allocation flag for PEDW4W";  
attrib  pxdwlkwk     length=3     label="Labor Force-allocation flag for PEDWLK";  
attrib  pxdwavl      length=3     label="Labor Force-allocation flag for D23c";  
attrib  pxdwavr      length=3     label="Labor Force-allocation flag for PEDWAV";  
attrib  pxjhwko      length=3     label="Labor Force-allocation flag for PEJHWK";  
attrib  pxjhrsn      length=3     label="Labor Force-allocation flag for PEJHRS";  
attrib  pxjhwant     length=3     label="Labor Force-allocation flag for PEJHWA";  
attrib  pxio1cow     length=3     label="Indus.& Occ.-allocation flag for PEIO1";  
attrib  pxio1icd     length=3     label="Indus.& Occ.-allocation flag for PEIO1";  
attrib  pxio1ocd     length=3     label="Indus.& Occ.-allocation flag for PEIO1";  
attrib  pxio2cow     length=3     label="Indus.& Occ.-allocation flag for PEI02";  
attrib  pxio2icd     length=3     label="Indus.& Occ.-allocation flag for PEIO2";  
attrib  pxio2ocd     length=3     label="Indus.& Occ.-allocation flag for PEIO2";  
attrib  pxernuot     length=3     label="Earnings-allocation flag for PEERNUOT";  
attrib  pxernper     length=3     label="Earnings-allocation flag for PEERNPER";  
attrib  pxernh1o     length=3     label="Earnings-allocation flag for PEERNH1O";  
attrib  pxernhro     length=3     label="Earnings-allocation flag for PEERNHRO";  
attrib  pxern        length=3     label="Earnings-allocation flag for PEERN";  
attrib  pxernwkp     length=3     label="Earnings-allocation flag for weeks pai";  
attrib  pxernrt      length=3     label="Earnings-allocation flag for PEERNRT";  
attrib  pxernhry     length=3     label="Earnings-allocation flag for PEERNHRY";  
attrib  pxernh2      length=3     label="Earnings-allocation flag for PEERNH1O";  
attrib  pxernlab     length=3     label="Earnings-allocation flag for PEERNLAB";  
attrib  pxerncov     length=3     label="Earnings-allocation flag for PEERNCOV";  
attrib  pxnlfjh      length=3     label="Labor Force-allocation flag for PENLFJ";  
attrib  pxnlfret     length=3     label="Labor Force-allocation flag for PENLFR";  
attrib  pxnlfact     length=3     label="Labor Force-allocation flag for PENLFA";  
attrib  pxschenr     length=3     label="School Enrollment-allocation flag for";  
attrib  pxschft      length=3     label="School Enrollment-allocation flag for";  
attrib  pxschlvl     length=3     label="School Enrollment-labor force allocati";  
attrib  qstnum       length=$5    label="Unique household identifier";     
attrib  occurnum     length=$2    label="Unique person identifier within a hous";  
attrib  pedipged     length=3     label="Demographics-high school,graduation/GE";  
attrib  pehgcomp     length=3     label="Demographics-highest grade completed b";  
attrib  pecyc        length=3     label="Demographics-years of college credit";  
attrib  pegrprof     length=3     label="Demographics-(have B.S./B.A.)taken";  
attrib  pegr6cor     length=3     label="Demographics-completed 6 or more gradu";  
attrib  pems123      length=3     label="Demographics-Master's program 1, 2, or";  
attrib  pxdipged     length=3     label="Demographics-allocation flag for PEDIP";  
attrib  pxhgcomp     length=3     label="Demographics-allocation flag for PEHGC";  
attrib  pxcyc        length=3     label="Demographics-allocation flag for PECYC";  
attrib  pxgrprof     length=3     label="Demographics-allocation flag for PEGRP";  
attrib  pxgr6cor     length=3     label="Demographics-allocation flag for PEGR6";  
attrib  pxms123      length=3     label="Demographics-allocation flag for PEMS1";  
attrib  pwcmpwgt     length=8     label="Weight-composited final weight";  


INPUT

@1    hrhhid     $15. 
@16   hrmonth      2. 
@18   hryear4      4. 
@22   hurespli     2. 
@24   hufinal      3. 
@27   huspnish     2. 
@29   hetenure     2. 
@31   hehousut     2. 
@33   hetelhhd     2. 
@35   hetelavl     2. 
@37   hephoneo     2. 
@39   hufaminc     2. 
@41   hutypea      2. 
@43   hutypb       2. 
@45   hutypc       2. 
@47   hwhhwgt    10.4 
@57   hrintsta     2. 
@59   hrnumhou     2. 
@61   hrhtype      2. 
@63   hrmis        2. 
@65   huinttyp     2. 
@67   huprscnt     2. 
@69   hrlonglk     2. 
@71   hrsample    $4. 
@75   hrsersuf    $2. 
@77   huhhnum      2. 
@79   hubus        2. 
@81   hubusl1      2. 
@83   hubusl2      2. 
@85   hubusl3      2. 
@87   hubusl4      2. 
@89   gereg        2. 
@91   gestcen      2. 
@93   gestfips     2. 
@95   gecmsa       2. 
@97   gemsa        4. 
@101  geco         3. 
@104  gemsast      1. 
@105  gemetsta     1. 
@106  geindvcc     1. 
@107  gemsasz      1. 
@108  gecmsasz     1. 
@109  hulensec     5. 
@114  proldrrp     2. 
@116  pupelig      2. 
@118  perrp        2. 
@120  peparent     2. 
@122  peage        2. 
@124  ptage        1. 
@125  pemaritl     2. 
@127  pespouse     2. 
@129  pesex        2. 
@131  puafever     2. 
@133  peafwhen     2. 
@135  peafnow      2. 
@137  peeduca      2. 
@139  perace       2. 
@141  prorigin     2. 
@143  puchinhh     2. 
@145  purelflg     2. 
@147  pulineno     2. 
@151  prfamnum     2. 
@153  prfamrel     2. 
@155  prfamtyp     2. 
@157  prhspnon     2. 
@159  prmarsta     2. 
@161  prpertyp     2. 
@163  penatvty     3. 
@166  pemntvty     3. 
@169  pefntvty     3. 
@172  prcitshp     2. 
@174  prcitflg     2. 
@176  prinusyr     2. 
@178  puslfprx     2. 
@180  pemlr        2. 
@182  puwk         2. 
@184  pubus1       2. 
@186  pubus2ot     2. 
@188  pubusck1     2. 
@190  pubusck2     2. 
@192  pubusck3     2. 
@194  pubusck4     2. 
@196  puretot      2. 
@198  pudis        2. 
@200  peret1       2. 
@202  pudis1       2. 
@204  pudis2       2. 
@206  puabsot      2. 
@208  pulay        2. 
@210  peabsrsn     2. 
@212  peabspdo     2. 
@214  pemjot       2. 
@216  pemjnum      2. 
@218  pehrusl1     2. 
@220  pehrusl2     2. 
@222  pehrftpt     2. 
@224  pehruslt     3. 
@227  pehrwant     2. 
@229  pehrrsn1     2. 
@231  pehrrsn2     2. 
@233  pehrrsn3     2. 
@235  puhroff1     2. 
@237  puhroff2     2. 
@239  puhrot1      2. 
@241  puhrot2      2. 
@243  pehract1     2. 
@245  pehract2     2. 
@247  pehractt     3. 
@250  pehravl      2. 
@252  pulbhsec     5. 
@257  puhrck1      2. 
@259  puhrck2      2. 
@261  puhrck3      2. 
@263  puhrck4      2. 
@265  puhrck5      2. 
@267  puhrck6      2. 
@269  puhrck7      2. 
@271  puhrck12     2. 
@273  pulaydt      2. 
@275  pulay6m      2. 
@277  pelayavl     2. 
@279  pulayavr     2. 
@281  pelaylk      2. 
@283  pelaydur     3. 
@286  pelayfto     2. 
@288  pulayck1     2. 
@290  pulayck2     2. 
@292  pulayck3     2. 
@294  pulk         2. 
@296  pelkm1       2. 
@298  pulkm2       2. 
@300  pulkm3       2. 
@302  pulkm4       2. 
@304  pulkm5       2. 
@306  pulkm6       2. 
@308  pulkdk1      2. 
@310  pulkdk2      2. 
@312  pulkdk3      2. 
@314  pulkdk4      2. 
@316  pulkdk5      2. 
@318  pulkdk6      2. 
@320  pulkps1      2. 
@322  pulkps2      2. 
@324  pulkps3      2. 
@326  pulkps4      2. 
@328  pulkps5      2. 
@330  pulkps6      2. 
@332  pelkavl      2. 
@334  pulkavr      2. 
@336  pelkll1o     2. 
@338  pelkll2o     2. 
@340  pelklwo      2. 
@342  pelkdur      3. 
@345  pelkfto      2. 
@347  pedwwnto     2. 
@349  pedwrsn      2. 
@351  pedwlko      2. 
@353  pedwwk       2. 
@355  pedw4wk      2. 
@357  pedwlkwk     2. 
@359  pedwavl      2. 
@361  pedwavr      2. 
@363  pudwck1      2. 
@365  pudwck2      2. 
@367  pudwck3      2. 
@369  pudwck4      2. 
@371  pudwck5      2. 
@373  pejhwko      2. 
@375  pujhdp1o     2. 
@377  pejhrsn      2. 
@379  pejhwant     2. 
@381  pujhck1      2. 
@383  pujhck2      2. 
@385  prabsrea     2. 
@387  prcivlf      2. 
@389  prdisc       2. 
@391  premphrs     2. 
@393  prempnot     2. 
@395  prexplf      2. 
@397  prftlf       2. 
@399  prhrusl      2. 
@401  prjobsea     2. 
@403  prpthrs      2. 
@405  prptrea      2. 
@407  prunedur     3. 
@410  prusftpt     2. 
@412  pruntype     2. 
@414  prwksch      2. 
@416  prwkstat     2. 
@418  prwntjob     2. 
@420  pujhck3      2. 
@422  pujhck4      2. 
@424  pujhck5      2. 
@426  puiodp1      2. 
@428  puiodp2      2. 
@430  puiodp3      2. 
@432  peio1cow     2. 
@434  puio1mfg     2. 
@436  peio1icd     3. 
@439  peio1ocd     3. 
@442  peio2cow     2. 
@444  puio2mfg     2. 
@446  peio2icd     3. 
@449  peio2ocd     3. 
@452  puiock1      2. 
@454  puiock2      2. 
@456  puiock3      2. 
@458  prioelg      2. 
@460  pragna       2. 
@462  prcow1       2. 
@464  prcow2       2. 
@466  prcowpg      2. 
@468  prdtcow1     2. 
@470  prdtcow2     2. 
@472  prdtind1     2. 
@474  prdtind2     2. 
@476  prdtocc1     2. 
@478  prdtocc2     2. 
@480  premp        2. 
@482  prmjind1     2. 
@484  prmjind2     2. 
@486  prmjocc1     2. 
@488  prmjocc2     2. 
@490  prmjocgr     2. 
@492  prnagpws     2. 
@494  prnagws      2. 
@496  prsjmj       2. 
@498  prerelg      2. 
@500  peernuot     2. 
@502  peernper     2. 
@504  peernrt      2. 
@506  peernhry     2. 
@508  puernh1c    4.2 
@512  peernh2     4.2 
@516  peernh1o    4.2 
@520  prernhly    4.2 
@524  pthr         1. 
@525  peernhro     2. 
@527  prernwa     8.2 
@535  ptwk         1. 
@540  peern       8.2 
@548  puern2      8.2 
@556  ptot         1. 
@559  peernwkp     2. 
@561  peernlab     2. 
@563  peerncov     2. 
@565  penlfjh      2. 
@567  penlfret     2. 
@569  penlfact     2. 
@571  punlfck1     2. 
@573  punlfck2     2. 
@575  peschenr     2. 
@577  peschft      2. 
@579  peschlvl     2. 
@581  prnlfsch     2. 
@583  pwfmwgt    10.4 
@593  pwlgwgt    10.4 
@603  pworwgt    10.4 
@613  pwsswgt    10.4 
@623  pwvetwgt   10.4 
@633  prchld       2. 
@635  prnmchld     2. 
@639  prwernal     2. 
@641  prhernal     2. 
@643  hxtenure     2. 
@645  hxhousut     2. 
@647  hxtelhhd     2. 
@649  hxtelavl     2. 
@651  hxphoneo     2. 
@653  pxinusyr     2. 
@655  pxrrp        2. 
@657  pxparent     2. 
@659  pxage        2. 
@661  pxmaritl     2. 
@663  pxspouse     2. 
@665  pxsex        2. 
@667  pxafwhen     2. 
@669  pxafnow      2. 
@671  pxeduca      2. 
@673  pxrace       2. 
@675  pxnatvty     2. 
@677  pxmntvty     2. 
@679  pxfntvty     2. 
@683  pxorigin     2. 
@685  pxmlr        2. 
@687  pxret1       2. 
@689  pxabsrsn     2. 
@691  pxabspdo     2. 
@693  pxmjot       2. 
@695  pxmjnum      2. 
@697  pxhrusl1     2. 
@699  pxhrusl2     2. 
@701  pxhrftpt     2. 
@703  pxhruslt     2. 
@705  pxhrwant     2. 
@707  pxhrrsn1     2. 
@709  pxhrrsn2     2. 
@711  pxhract1     2. 
@713  pxhract2     2. 
@715  pxhractt     2. 
@717  pxhrrsn3     2. 
@719  pxhravl      2. 
@721  pxlayavl     2. 
@723  pxlaylk      2. 
@725  pxlaydur     2. 
@727  pxlayfto     2. 
@729  pxlkm1       2. 
@731  pxlkavl      2. 
@733  pxlkll1o     2. 
@735  pxlkll2o     2. 
@737  pxlklwo      2. 
@739  pxlkdur      2. 
@741  pxlkfto      2. 
@743  pxdwwnto     2. 
@745  pxdwrsn      2. 
@747  pxdwlko      2. 
@749  pxdwwk       2. 
@751  pxdw4wk      2. 
@753  pxdwlkwk     2. 
@755  pxdwavl      2. 
@757  pxdwavr      2. 
@759  pxjhwko      2. 
@761  pxjhrsn      2. 
@763  pxjhwant     2. 
@765  pxio1cow     2. 
@767  pxio1icd     2. 
@769  pxio1ocd     2. 
@771  pxio2cow     2. 
@773  pxio2icd     2. 
@775  pxio2ocd     2. 
@777  pxernuot     2. 
@779  pxernper     2. 
@781  pxernh1o     2. 
@783  pxernhro     2. 
@785  pxern        2. 
@791  pxernwkp     2. 
@793  pxernrt      2. 
@795  pxernhry     2. 
@797  pxernh2      2. 
@799  pxernlab     2. 
@801  pxerncov     2. 
@803  pxnlfjh      2. 
@805  pxnlfret     2. 
@807  pxnlfact     2. 
@809  pxschenr     2. 
@811  pxschft      2. 
@813  pxschlvl     2. 
@815  qstnum      $5. 
@820  occurnum    $2. 
@822  pedipged     2. 
@824  pehgcomp     2. 
@826  pecyc        2. 
@828  pegrprof     2. 
@830  pegr6cor     2. 
@832  pems123      2. 
@834  pxdipged     2. 
@836  pxhgcomp     2. 
@838  pxcyc        2. 
@840  pxgrprof     2. 
@842  pxgr6cor     2. 
@844  pxms123      2. 
@846  pwcmpwgt   10.4 
;