attrib  hrhhid       length=$15   label="HOUSEHOLD IDENTIFIER	(Part 1)";   
attrib  hrmonth      length=3     label="MONTH OF INTERVIEW";              
attrib  hryear4      length=4     label="YEAR OF INTERVIEW";               
attrib  hurespli     length=3     label="LINE NUMBER OF THE CURRENT";      
attrib  hufinal      length=3     label="FINAL OUTCOME CODE";              
attrib  huspnish     length=3     label="IS SPANISH THE ONLY LANGUAGE SPOKEN";  
attrib  hetenure     length=3     label="ARE YOUR LIVING QUARTERS...";     
attrib  hehousut     length=3     label="TYPE OF HOUSING UNIT";            
attrib  hetelhhd     length=3     label="IS THERE A TELEPHONE IN THIS";    
attrib  hetelavl     length=3     label="IS THERE A TELEPHONE ELSEWHERE ON";  
attrib  hephoneo     length=3     label="IS A TELEPHONE INTERVIEW ACCEPTABLE?";  
attrib  hefaminc     length=3     label="FAMILY INCOME";                   
attrib  hutypea      length=3     label="TYPE A NONINTERVIEW REASON";      
attrib  hutypb       length=3     label="TYPE B NON-INTERVIEW REASON";     
attrib  hutypc       length=3     label="TYPE C NON-INTERVIEW REASON";     
attrib  hwhhwgt      length=8     label="HOUSEHOLD WEIGHT";                
attrib  hrintsta     length=3     label="INTERVIEW STATUS";                
attrib  hrnumhou     length=3     label="TOTAL NUMBER OF PERSONS LIVING";  
attrib  hrhtype      length=3     label="HOUSEHOLD TYPE";                  
attrib  hrmis        length=3     label="MONTH-IN-SAMPLE";                 
attrib  huinttyp     length=3     label="TYPE OF INTERVIEW";               
attrib  huprscnt     length=3     label="NUMBER OF ACTUAL AND";            
attrib  hrlonglk     length=3     label="LONGITUDINAL LINK INDICATOR";     
attrib  hrhhid2      length=$5    label="HOUSEHOLD IDENTIFIER (part 2)";   
attrib  hubus        length=3     label="DOES ANYONE IN THIS HOUSEHOLD";   
attrib  hubusl1      length=3     label="ENTER LINE NUMBER";               
attrib  hubusl2      length=3     label="See BUSL1";                       
attrib  hubusl3      length=3     label="See BUSL1";                       
attrib  hubusl4      length=3     label="See BUSL1";                       
attrib  gereg        length=3     label="REGION";                          
attrib  gestcen      length=3     label="CENSUS STATE CODE";               
attrib  gestfips     length=3     label="FEDERAL INFORMATION";             
attrib  gtcbsa       length=4     label="Metropolitan CBSA FIPS CODE";     
attrib  gtco         length=3     label="FIPS COUNTY CODE";                
attrib  gtcbsast     length=3     label="PRINCIPAL CITY/BALANCE STATUS";   
attrib  gtmetsta     length=3     label="METROPOLITAN STATUS";             
attrib  gtindvpc     length=3     label="INDIVIDUAL PRINCIPAL CITY";       
attrib  gtcbsasz     length=3     label="Metropolitan Area (CBSA) SIZE";   
attrib  gtcsa        length=3     label="Consolidated Statistical Area (CSA) FI";  
attrib  proldrrp     length=3     label="RELATIONSHIP TO REFERENCE";       
attrib  pupelig      length=3     label="INTERVIEW STATUS OF EACH PERSON";  
attrib  perrp        length=3     label="RELATIONSHIP TO REFERENCE PERSON";  
attrib  peparent     length=3     label="LINE NUMBER OF PARENT";           
attrib  prtage       length=3     label="PERSONS AGE";                     
attrib  prtfage      length=3     label="TOP CODE FLAG FOR AGE";           
attrib  pemaritl     length=3     label="MARITAL STATUS";                  
attrib  pespouse     length=3     label="LINE NUMBER OF SPOUSE";           
attrib  pesex        length=3     label="SEX";                             
attrib  peafever     length=3     label="DID YOU EVER SERVE ON ACTIVE";    
attrib  peafnow      length=3     label="ARE YOU NOW IN THE ARMED FORCES";  
attrib  peeduca      length=3     label="HIGHEST LEVEL OF SCHOOL";         
attrib  ptdtrace     length=3     label="RACE";                            
attrib  prdthsp      length=3     label="DETAILED HISPANIC 	ORIGIN GROUP";  
attrib  puchinhh     length=3     label="CHANGE IN HOUSEHOLD COMPOSITION";  
attrib  pulineno     length=3     label="PERSON'S LINE NUMBER";            
attrib  prfamnum     length=3     label="FAMILY NUMBER RECODE";            
attrib  prfamrel     length=3     label="FAMILY RELATIONSHIP RECODE";      
attrib  prfamtyp     length=3     label="FAMILY TYPE RECODE";              
attrib  pehspnon     length=3     label="HISPANIC OR NON-HISPANIC";        
attrib  prmarsta     length=3     label="MARITAL STATUS BASED ON";         
attrib  prpertyp     length=3     label="TYPE OF PERSON RECORD RECODE";    
attrib  penatvty     length=3     label="COUNTRY OF BIRTH";                
attrib  pemntvty     length=3     label="MOTHER'S COUNTRY OF BIRTH";       
attrib  pefntvty     length=3     label="FATHER'S COUNTRY OF BIRTH";       
attrib  prcitshp     length=3     label="CITIZENSHIP STATUS";              
attrib  prcitflg     length=3     label="CITIZENSHIP ALLOCATION FLAG";     
attrib  prinusyr     length=3     label="IMMIGRANT'S YEAR OF ENTRY";       
attrib  puslfprx     length=3     label="LABOR FORCE INFORMATION COLLECTED";  
attrib  pemlr        length=3     label="MONTHLY LABOR FORCE RECODE";      
attrib  puwk         length=3     label="LAST WEEK, DID YOU DO ANY WORK";  
attrib  pubus1       length=3     label="LAST WEEK, DID YOU DO ANY";       
attrib  pubus2ot     length=3     label="DO YOU RECEIVE ANY PAYMENTS";     
attrib  pubusck1     length=3     label="CHECK ITEM 1";                    
attrib  pubusck2     length=3     label="CHECK ITEM 2";                    
attrib  pubusck3     length=3     label="CHECK ITEM 3";                    
attrib  pubusck4     length=3     label="CHECK ITEM 4";                    
attrib  puretot      length=3     label="RETIREMENT STATUS";               
attrib  pudis        length=3     label="DISABILITY STATUS";               
attrib  peret1       length=3     label="DO YOU CURRENTLY WANT A JOB, EITHER";  
attrib  pudis1       length=3     label="DOES YOUR DISABILITY PREVENT YOU FROM";  
attrib  pudis2       length=3     label="DO YOU HAVE A DISABILITY THAT PREVENTS";  
attrib  puabsot      length=3     label="LAST WEEK DID YOU HAVE A JOB";    
attrib  pulay        length=3     label="LAST WEEK, WERE YOU ON LAYOFF";   
attrib  peabsrsn     length=3     label="WHAT IS THE MAIN REASON YOU";     
attrib  peabspdo     length=3     label="ARE YOU BEING PAID BY YOUR";      
attrib  pemjot       length=3     label="DO YOU HAVE MORE THAN ONE JOB?";  
attrib  pemjnum      length=3     label="ALTOGETHER, HOW MANY JOBS";       
attrib  pehrusl1     length=3     label="HOW MANY HOURS PER WEEK DO YOU";  
attrib  pehrusl2     length=3     label="HOW MANY HOURS PER WEEK DO YOU";  
attrib  pehrftpt     length=3     label="DO YOU USUALLY WORK 35 HOURS OR";  
attrib  pehruslt     length=3     label="SUM OF HRUSL1 AND HRUSL2.";       
attrib  pehrwant     length=3     label="DO YOU WANT TO WORK A FULL-TIME";  
attrib  pehrrsn1     length=3     label="WHAT IS YOUR MAIN REASON FOR";    
attrib  pehrrsn2     length=3     label="WHAT IS THE MAIN REASON YOU DO NOT";  
attrib  pehrrsn3     length=3     label="WHAT IS THE MAIN REASON YOU WORKED";  
attrib  puhroff1     length=3     label="LAST WEEK, DID YOU LOSE OR TAKE";  
attrib  puhroff2     length=3     label="HOW MANY HOURS DID YOU TAKE OFF?";  
attrib  puhrot1      length=3     label="LAST WEEK, DID YOU WORK ANY";     
attrib  puhrot2      length=3     label="HOW MANY ADDITIONAL HOURS";       
attrib  pehract1     length=3     label="LAST WEEK, HOW MANY HOURS DID YOU";  
attrib  pehract2     length=3     label="LAST WEEK, HOW MANY HOURS DID";   
attrib  pehractt     length=3     label="SUM OF PEHRACT1 AND PEHRACT2.";   
attrib  pehravl      length=3     label="LAST WEEK, COULD YOU HAVE WORKED";  
attrib  puhrck1      length=3     label="CHECK ITEM 1";                    
attrib  puhrck2      length=3     label="CHECK ITEM 2";                    
attrib  puhrck3      length=3     label="CHECK ITEM 3";                    
attrib  puhrck4      length=3     label="CHECK ITEM 4";                    
attrib  puhrck5      length=3     label="CHECK ITEM 5";                    
attrib  puhrck6      length=3     label="CHECK ITEM 6";                    
attrib  puhrck7      length=3     label="CHECK ITEM 7";                    
attrib  puhrck12     length=3     label="CHECK ITEM 12";                   
attrib  pulaydt      length=3     label="HAS YOUR EMPLOYER GIVEN YOU A DATE";  
attrib  pulay6m      length=3     label="HAVE YOU BEEN GIVEN ANY INDICATION";  
attrib  pelayavl     length=3     label="COULD YOU HAVE RETURNED TO WORK";  
attrib  pulayavr     length=3     label="WHY IS THAT?";                    
attrib  pelaylk      length=3     label="EVEN THOUGH YOU ARE TO BE CALLED BACK";  
attrib  pelaydur     length=3     label="DURATION OF LAYOFF";              
attrib  pelayfto     length=3     label="FT/PT STATUS OF JOB FROM WHICH";  
attrib  pulayck1     length=3     label="CHECK ITEM 1";                    
attrib  pulayck2     length=3     label="CHECK ITEM 2";                    
attrib  pulayck3     length=3     label="CHECK ITEM 3";                    
attrib  pulk         length=3     label="HAVE YOU BEEN DOING ANYTHING TO FIND";  
attrib  pelkm1       length=3     label="WHAT ARE ALL OF THE THINGS YOU HAVE";  
attrib  pulkm2       length=3     label="ANYTHING ELSE? (SECOND METHOD)";  
attrib  pulkm3       length=3     label="SAME AS PULKM2 (THIRD METHOD)";   
attrib  pulkm4       length=3     label="SAME AS PULKM2 (FOURTH METHOD)";  
attrib  pulkm5       length=3     label="SAME AS PULKM2 (FIFTH METHOD)";   
attrib  pulkm6       length=3     label="SAME AS PULKM2 (SIXTH METHOD)";   
attrib  pulkdk1      length=3     label="YOU SAID YOU HAVE BEEN TRYING TO";  
attrib  pulkdk2      length=3     label="ANYTHING ELSE? (SECOND METHOD)";  
attrib  pulkdk3      length=3     label="SAME AS PULKDK2 (THIRD METHOD)";  
attrib  pulkdk4      length=3     label="SAME AS PULKDK2 (FOURTH METHOD)";  
attrib  pulkdk5      length=3     label="SAME AS PULKDK2 (FIFTH METHOD)";  
attrib  pulkdk6      length=3     label="SAME AS PULKDK2 (SIXTH METHOD)";  
attrib  pulkps1      length=3     label="CAN YOU TELL ME MORE ABOUT WHAT YOU";  
attrib  pulkps2      length=3     label="ANYTHING ELSE? (SECOND METHOD)";  
attrib  pulkps3      length=3     label="SAME AS PULKPS2 (THIRD METHOD)";  
attrib  pulkps4      length=3     label="SAME AS PULKPS2 (FOURTH METHOD)";  
attrib  pulkps5      length=3     label="SAME AS PULKPS2 (FIFTH METHOD)";  
attrib  pulkps6      length=3     label="SAME AS PULKPS2 (SIXTH METHOD)";  
attrib  pelkavl      length=3     label="LAST WEEK, COULD YOU HAVE STARTED";  
attrib  pulkavr      length=3     label="WHY IS THAT?";                    
attrib  pelkll1o     length=3     label="BEFORE YOU STARTED LOOKING FOR WORK,";  
attrib  pelkll2o     length=3     label="DID YOU LOSE OR QUIT THAT JOB, OR WAS ";  
attrib  pelklwo      length=3     label="WHEN LAST WORKED";                
attrib  pelkdur      length=3     label="DURATION OF JOB SEEKING";         
attrib  pelkfto      length=3     label="FT/PT STATUS OF JOBSEEKER";       
attrib  pedwwnto     length=3     label="DO YOU CURRENTLY WANT A JOB,";    
attrib  pedwrsn      length=3     label="WHAT IS THE MAIN REASON YOU WERE NOT";  
attrib  pedwlko      length=3     label="DID YOU LOOK FOR WORK AT ANY TIME";  
attrib  pedwwk       length=3     label="DID YOU ACTUALLY WORK AT A JOB OR";  
attrib  pedw4wk      length=3     label="DID YOU DO ANY OF THIS WORK DURING";  
attrib  pedwlkwk     length=3     label="SINCE YOU LEFT THAT JOB OR";      
attrib  pedwavl      length=3     label="LAST WEEK, COULD YOU HAVE STARTED";  
attrib  pedwavr      length=3     label="WHY IS THAT?";                    
attrib  pudwck1      length=3     label="SCREEN FOR DISCOURAGED WORKERS";  
attrib  pudwck2      length=3     label="SCREEN FOR DISABLED";             
attrib  pudwck3      length=3     label="FILTER FOR RETIRED";              
attrib  pudwck4      length=3     label="FILTER FOR PASSIVE JOB SEEKERS";  
attrib  pudwck5      length=3     label="FILTER FOR PASSIVE JOB SEEKERS";  
attrib  pejhwko      length=3     label="HAVE YOU WORKED AT A JOB OR BUSINESS";  
attrib  pujhdp1o     length=3     label="DID YOU DO ANY OF THIS WORK IN";  
attrib  pejhrsn      length=3     label="WHAT IS THE MAIN REASON YOU LEFT";  
attrib  pejhwant     length=3     label="DO YOU INTEND TO LOOK FOR WORK DURING";  
attrib  pujhck1      length=3     label="FILTER FOR OUTGOING ROTATIONS";   
attrib  pujhck2      length=3     label="FILTER FOR PERSONS GOING THROUGH THE";  
attrib  prabsrea     length=3     label="REASON NOT AT WORK AND PAY STATUS";  
attrib  prcivlf      length=3     label="CIVILIAN LABOR FORCE";            
attrib  prdisc       length=3     label="DISCOURAGED WORKER RECODE";       
attrib  premphrs     length=3     label="REASON NOT AT WORK OR HOURS AT WORK";  
attrib  prempnot     length=3     label="MLR - EMPLOYED, UNEMPLOYED, OR NILF";  
attrib  prexplf      length=3     label="EXPERIENCED LABOR FORCE EMPLOYMENT";  
attrib  prftlf       length=3     label="FULL TIME LABOR FORCE";           
attrib  prhrusl      length=3     label="USUAL HOURS WORKED WEEKLY";       
attrib  prjobsea     length=3     label="JOB SEARCH RECODE";               
attrib  prpthrs      length=3     label="AT WORK 1-34 BY HOURS AT WORK";   
attrib  prptrea      length=3     label="DETAILED REASON FOR PART-TIME";   
attrib  prunedur     length=3     label="DURATION OF UNEMPLOYMENT FOR";    
attrib  pruntype     length=3     label="REASON FOR UNEMPLOYMENT";         
attrib  prwksch      length=3     label="LABOR FORCE BY TIME";             
attrib  prwkstat     length=3     label="FULL/PART-TIME WORK STATUS";      
attrib  prwntjob     length=3     label="NILF RECODE - WANT A JOB OR OTHER NILF";  
attrib  pujhck3      length=3     label="JOB HISTORY CHECK ITEM";          
attrib  pujhck4      length=3     label="SCREEN FOR DEPENDENT NILF";       
attrib  pujhck5      length=3     label="SCREEN FOR DEPENDENT NILF";       
attrib  puiodp1      length=3     label="LAST MONTH, IT WAS REPORTED THAT YOU";  
attrib  puiodp2      length=3     label="HAVE THE USUAL ACTIVITIES AND DUTIES";  
attrib  puiodp3      length=3     label="LAST MONTH YOU WERE REPORTED AS (A/AN)";  
attrib  peio1cow     length=3     label="INDIVIDUAL CLASS OF WORKER CODE";  
attrib  puio1mfg     length=3     label="IS THIS BUSINESS OR ORGANIZATION MAINL";  
attrib  peio2cow     length=3     label="INDIVIDUAL CLASS OF WORKER ON";   
attrib  puio2mfg     length=3     label="IS THIS BUSINESS OR ORGANIZATION MAINL";  
attrib  puiock1      length=3     label="I & O CHECK ITEM 1";              
attrib  puiock2      length=3     label="I & O CHECK ITEM 2";              
attrib  puiock3      length=3     label="I & O CHECK ITEM 3";              
attrib  prioelg      length=3     label="INDUSTRY AND OCCUPATION";         
attrib  pragna       length=3     label="AGRICULTURE/";                    
attrib  prcow1       length=3     label="CLASS OF WORKER";                 
attrib  prcow2       length=3     label="CLASS OF WORKER";                 
attrib  prcowpg      length=3     label="COW - PRIVATE OR GOVERNMENT";     
attrib  prdtcow1     length=3     label="DETAILED CLASS OF WORKER RECODE - JOB ";  
attrib  prdtcow2     length=3     label="DETAILED CLASS OF WORKER RECODE - JOB ";  
attrib  prdtind1     length=3     label="DETAILED INDUSTRY RECODE - JOB 1";  
attrib  prdtind2     length=3     label="DETAILED INDUSTRY RECODE - JOB 2";  
attrib  prdtocc1     length=3     label="DETAILED OCCUPATION RECODE - JOB 1";  
attrib  prdtocc2     length=3     label="DETAILED OCCUPATION RECODE";      
attrib  premp        length=3     label="EMPLOYED PERSONS (NON-FARM";      
attrib  prmjind1     length=3     label="MAJOR INDUSTRY RECODE - JOB 1";   
attrib  prmjind2     length=3     label="MAJOR INDUSTRY RECODE - JOB 2";   
attrib  prmjocc1     length=3     label="MAJOR OCCUPATION RECODE - JOB 1";  
attrib  prmjocc2     length=3     label="MAJOR OCCUPATION RECODE - JOB 2";  
attrib  prmjocgr     length=3     label="MAJOR OCCUPATION CATEGORIES";     
attrib  prnagpws     length=3     label="NON-AGRICULTURE, PRIVATE";        
attrib  prnagws      length=3     label="NON-AGRICULTURE WAGE AND";        
attrib  prsjmj       length=3     label="SINGLE/MULTIPLE JOBHOLDER";       
attrib  prerelg      length=3     label="EARNINGS ELIGIBILITY FLAG";       
attrib  peernuot     length=3     label="DO YOU USUALLY RECEIVE OVERTIME PAY,";  
attrib  peernper     length=3     label="PERIODICITY";                     
attrib  peernrt      length=3     label="(EVEN THOUGH YOU TOLD ME IT IS EASIER";  
attrib  peernhry     length=3     label="HOURLY/NONHOURLY STATUS";         
attrib  puernh1c     length=8     label="WHAT IS YOUR HOURLY RATE OF PAY ON";  
attrib  peernh2      length=8     label="(EXCLUDING OVERTIME PAY, TIPS AND";  
attrib  peernh1o     length=8     label="OUT VARIABLE FOR HOURLY";         
attrib  prernhly     length=8     label="RECODE FOR HOURLY RATE";          
attrib  pthr         length=3     label="HOURLY PAY - TOP CODE";           
attrib  peernhro     length=3     label="USUAL HOURS";                     
attrib  prernwa      length=8     label="WEEKLY EARNINGS RECODE";          
attrib  ptwk         length=3     label="WEEKLY EARNINGS - TOP CODE";      
attrib  peern        length=8     label="CALCULATED WEEKLY OVERTIME AMOUNT";  
attrib  puern2       length=8     label="CALCULATED WEEKLY";               
attrib  ptot         length=3     label="WEEKLY OVERTIME AMOUNT - TOP CODE";  
attrib  peernwkp     length=3     label="HOW MANY WEEKS A YEAR DO YOU";    
attrib  peernlab     length=3     label="ON THIS JOB, ARE YOU A MEMBER OF A";  
attrib  peerncov     length=3     label="ON THIS JOB ARE YOU COVERED BY A UNION";  
attrib  penlfjh      length=3     label="WHEN DID YOU LAST WORK AT A JOB";  
attrib  penlfret     length=3     label="ARE YOU RETIRED FROM A JOB";      
attrib  penlfact     length=3     label="WHAT BEST DESCRIBES YOUR SITUATION AT";  
attrib  punlfck1     length=3     label="NOT IN LABOR FORCE";              
attrib  punlfck2     length=3     label="NOT IN LABOR FORCE";              
attrib  peschenr     length=3     label="LAST WEEK, WERE YOU ENROLLED IN A";  
attrib  peschft      length=3     label="ARE YOU ENROLLED IN SCHOOL AS A";  
attrib  peschlvl     length=3     label="WOULD THAT BE HIGH SCHOOL, COLLEGE,";  
attrib  prnlfsch     length=3     label="NLF ACTIVITY - IN SCHOOL OR NOT IN SCH";  
attrib  pwfmwgt      length=8     label="FAMILY WEIGHT";                   
attrib  pwlgwgt      length=8     label="LONGITUDINAL WEIGHT";             
attrib  pworwgt      length=8     label="OUTGOING ROTATION WEIGHT";        
attrib  pwsswgt      length=8     label="FINAL WEIGHT";                    
attrib  pwvetwgt     length=8     label="VETERANS WEIGHT";                 
attrib  prchld       length=3     label="PRESENCE OF OWN CHILDREN <18 YEARS";  
attrib  prnmchld     length=3     label="Number of own children <18 years of ag";  
attrib  prwernal     length=3     label="ALLOCATION FLAG";                 
attrib  prhernal     length=3     label="ALLOCATION FLAG";                 
attrib  hxtenure     length=3     label="ALLOCATION FLAG";                 
attrib  hxhousut     length=3     label="ALLOCATION FLAG";                 
attrib  hxtelhhd     length=3     label="ALLOCATION FLAG";                 
attrib  hxtelavl     length=3     label="ALLOCATION FLAG";                 
attrib  hxphoneo     length=3     label="ALLOCATION FLAG";                 
attrib  pxinusyr     length=3     label="ALLOCATION FLAG";                 
attrib  pxrrp        length=3     label="ALLOCATION FLAG";                 
attrib  pxparent     length=3     label="ALLOCATION FLAG";                 
attrib  pxage        length=3     label="ALLOCATION FLAG";                 
attrib  pxmaritl     length=3     label="ALLOCATION FLAG";                 
attrib  pxspouse     length=3     label="ALLOCATION FLAG";                 
attrib  pxsex        length=3     label="ALLOCATION FLAG";                 
attrib  pxafwhn1     length=3     label="ALLOCATION FLAG";                 
attrib  pxafnow      length=3     label="ALLOCATION FLAG";                 
attrib  pxeduca      length=3     label="ALLOCATION FLAG";                 
attrib  pxrace1      length=3     label="ALLOCATION FLAG";                 
attrib  pxnatvty     length=3     label="ALLOCATION FLAG";                 
attrib  pxmntvty     length=3     label="ALLOCATION FLAG";                 
attrib  pxfntvty     length=3     label="ALLOCATION FLAG";                 
attrib  pxhspnon     length=3     label="ALLOCATION FLAG";                 
attrib  pxmlr        length=3     label="ALLOCATION FLAG";                 
attrib  pxret1       length=3     label="ALLOCATION FLAG";                 
attrib  pxabsrsn     length=3     label="ALLOCATION FLAG";                 
attrib  pxabspdo     length=3     label="ALLOCATION FLAG";                 
attrib  pxmjot       length=3     label="ALLOCATION FLAG";                 
attrib  pxmjnum      length=3     label="ALLOCATION FLAG";                 
attrib  pxhrusl1     length=3     label="ALLOCATION FLAG";                 
attrib  pxhrusl2     length=3     label="ALLOCATION FLAG";                 
attrib  pxhrftpt     length=3     label="ALLOCATION FLAG";                 
attrib  pxhruslt     length=3     label="ALLOCATION FLAG";                 
attrib  pxhrwant     length=3     label="ALLOCATION FLAG";                 
attrib  pxhrrsn1     length=3     label="ALLOCATION FLAG";                 
attrib  pxhrrsn2     length=3     label="ALLOCATION FLAG";                 
attrib  pxhract1     length=3     label="ALLOCATION FLAG";                 
attrib  pxhract2     length=3     label="ALLOCATION FLAG";                 
attrib  pxhractt     length=3     label="ALLOCATION FLAG";                 
attrib  pxhrrsn3     length=3     label="ALLOCATION FLAG";                 
attrib  pxhravl      length=3     label="ALLOCATION FLAG";                 
attrib  pxlayavl     length=3     label="ALLOCATION FLAG";                 
attrib  pxlaylk      length=3     label="ALLOCATION FLAG";                 
attrib  pxlaydur     length=3     label="ALLOCATION FLAG";                 
attrib  pxlayfto     length=3     label="ALLOCATION FLAG";                 
attrib  pxlkm1       length=3     label="ALLOCATION FLAG";                 
attrib  pxlkavl      length=3     label="ALLOCATION FLAG";                 
attrib  pxlkll1o     length=3     label="ALLOCATION FLAG";                 
attrib  pxlkll2o     length=3     label="ALLOCATION FLAG";                 
attrib  pxlklwo      length=3     label="ALLOCATION FLAG";                 
attrib  pxlkdur      length=3     label="ALLOCATION FLAG";                 
attrib  pxlkfto      length=3     label="ALLOCATION FLAG";                 
attrib  pxdwwnto     length=3     label="ALLOCATION FLAG";                 
attrib  pxdwrsn      length=3     label="ALLOCATION FLAG";                 
attrib  pxdwlko      length=3     label="ALLOCATION FLAG";                 
attrib  pxdwwk       length=3     label="ALLOCATION FLAG";                 
attrib  pxdw4wk      length=3     label="ALLOCATION FLAG";                 
attrib  pxdwlkwk     length=3     label="ALLOCATION FLAG";                 
attrib  pxdwavl      length=3     label="ALLOCATION FLAG";                 
attrib  pxdwavr      length=3     label="ALLOCATION FLAG";                 
attrib  pxjhwko      length=3     label="ALLOCATION FLAG";                 
attrib  pxjhrsn      length=3     label="ALLOCATION FLAG";                 
attrib  pxjhwant     length=3     label="ALLOCATION FLAG";                 
attrib  pxio1cow     length=3     label="ALLOCATION FLAG";                 
attrib  pxio1icd     length=3     label="ALLOCATION FLAG";                 
attrib  pxio1ocd     length=3     label="ALLOCATION FLAG";                 
attrib  pxio2cow     length=3     label="ALLOCATION FLAG";                 
attrib  pxio2icd     length=3     label="ALLOCATION FLAG";                 
attrib  pxio2ocd     length=3     label="ALLOCATION FLAG";                 
attrib  pxernuot     length=3     label="ALLOCATION FLAG";                 
attrib  pxernper     length=3     label="ALLOCATION FLAG";                 
attrib  pxernh1o     length=3     label="ALLOCATION FLAG";                 
attrib  pxernhro     length=3     label="ALLOCATION FLAG";                 
attrib  pxern        length=3     label="ALLOCATION FLAG";                 
attrib  pxernwkp     length=3     label="ALLOCATION FLAG";                 
attrib  pxernrt      length=3     label="ALLOCATION FLAG";                 
attrib  pxernhry     length=3     label="ALLOCATION FLAG";                 
attrib  pxernh2      length=3     label="ALLOCATION FLAG";                 
attrib  pxernlab     length=3     label="ALLOCATION FLAG";                 
attrib  pxerncov     length=3     label="ALLOCATION FLAG";                 
attrib  pxnlfjh      length=3     label="ALLOCATION FLAG";                 
attrib  pxnlfret     length=3     label="ALLOCATION FLAG";                 
attrib  pxnlfact     length=3     label="ALLOCATION FLAG";                 
attrib  pxschenr     length=3     label="ALLOCATION FLAG";                 
attrib  pxschft      length=3     label="ALLOCATION FLAG";                 
attrib  pxschlvl     length=3     label="ALLOCATION FLAG";                 
attrib  qstnum       length=$5    label="Unique household identifier. Valid onl";  
attrib  occurnum     length=$2    label="Unique person identifier. Valid only w";  
attrib  pedipged     length=3     label="How did...get...'s high school diploma";  
attrib  pehgcomp     length=3     label="What was the highest grade of regular";  
attrib  pecyc        length=3     label="How many years of college credit has..";  
attrib  pegrprof     length=3     label="Since completing...bachelor's degree, ";  
attrib  pegr6cor     length=3     label="Did...complete 6 or more graduate or p";  
attrib  pems123      length=3     label="Was ... master's degree program a 1 ye";  
attrib  pxdipged     length=3     label="ALLOCATION FLAG";                 
attrib  pxhgcomp     length=3     label="ALLOCATION FLAG";                 
attrib  pxcyc        length=3     label="ALLOCATION FLAG";                 
attrib  pxgrprof     length=3     label="ALLOCATION FLAG";                 
attrib  pxgr6cor     length=3     label="ALLOCATION FLAG";                 
attrib  pxms123      length=3     label="ALLOCATION FLAG";                 
attrib  pwcmpwgt     length=8     label="Composited Final Weight. Used to creat";  
attrib  peio1icd     length=4     label="INDUSTRY CODE FOR PRIMARY JOB";   
attrib  peio1ocd     length=4     label="OCCUPATION CODE FOR PRIMARY JOB.";  
attrib  peio2icd     length=4     label="INDUSTRY CODE FOR SECOND JOB.";   
attrib  peio2ocd     length=4     label="OCCUPATION CODE FOR SECOND JOB.";  
attrib  primind1     length=3     label="INTERMEDIATE INDUSTRY RECODE (JOB 1)";  
attrib  primind2     length=3     label="INTERMEDIATE INDUSTRY RECODE (JOB 2)";  
attrib  peafwhn1     length=3     label="WHEN DID YOU SERVE?";             
attrib  peafwhn2     length=3     label="WHEN DID YOU SERVE?";             
attrib  peafwhn3     length=3     label="WHEN DID YOU SERVE?";             
attrib  peafwhn4     length=3     label="WHEN DID YOU SERVE?";             
attrib  pxafever     length=3     label="ALLOCATION FLAG";                 
attrib  pelndad      length=3     label="LINE NUMBER OF FATHER";           
attrib  pelnmom      length=3     label="LINE NUMBER OF MOTHER";           
attrib  pedadtyp     length=3     label="TYPE OF FATHER";                  
attrib  pemomtyp     length=3     label="TYPE OF MOTHER";                  
attrib  pecohab      length=3     label="LINE NUMBER OF COHABITING PARTNER";  
attrib  pxlndad      length=3     label="ALLOCATION FLAG";                 
attrib  pxlnmom      length=3     label="ALLOCATION FLAG";                 
attrib  pxdadtyp     length=3     label="ALLOCATION FLAG";                 
attrib  pxmomtyp     length=3     label="ALLOCATION FLAG";                 
attrib  pxcohab      length=3     label="ALLOCATION FLAG";                 
attrib  pedisear     length=3     label="IS...DEAF OR DOES...HAVE SERIOUS";  
attrib  pediseye     length=3     label="IS...BLIND OR DOES...HAVE SERIOUS";  
attrib  pedisrem     length=3     label="BECAUSE OF A PHYSICAL, MENTAL, OR";  
attrib  pedisphy     length=3     label="DOES...HAVE SERIOUS DIFFICULTY";  
attrib  pedisdrs     length=3     label="DOES ... HAVE DIFFICULTY";        
attrib  pedisout     length=3     label="BECAUSE OF A PHYSICAL, MENTAL, OR";  
attrib  prdisflg     length=3     label="DOES THIS PERSON HAVE ANY OF";    
attrib  pxdisear     length=3     label="ALLOCATION FLAG";                 
attrib  pxdiseye     length=3     label="ALLOCATION FLAG";                 
attrib  pxdisrem     length=3     label="ALLOCATION FLAG";                 
attrib  pxdisphy     length=3     label="ALLOCATION FLAG";                 
attrib  pxdisdrs     length=3     label="ALLOCATION FLAG";                 
attrib  pxdisout     length=3     label="ALLOCATION FLAG";                 
attrib  hxfaminc     length=3     label="ALLOCATION FLAG";                 
attrib  prdasian     length=3     label="DETAILED ASIAN RACE RECODE";      


INPUT

@1    hrhhid     $15. 
@16   hrmonth      2. 
@18   hryear4      4. 
@22   hurespli     2. 
@24   hufinal      3. 
@27   huspnish     2. 
@29   hetenure     2. 
@31   hehousut     2. 
@33   hetelhhd     2. 
@35   hetelavl     2. 
@37   hephoneo     2. 
@39   hefaminc     2. 
@41   hutypea      2. 
@43   hutypb       2. 
@45   hutypc       2. 
@47   hwhhwgt    10.4 
@57   hrintsta     2. 
@59   hrnumhou     2. 
@61   hrhtype      2. 
@63   hrmis        2. 
@65   huinttyp     2. 
@67   huprscnt     2. 
@69   hrlonglk     2. 
@71   hrhhid2     $5. 
@79   hubus        2. 
@81   hubusl1      2. 
@83   hubusl2      2. 
@85   hubusl3      2. 
@87   hubusl4      2. 
@89   gereg        2. 
@91   gestcen      2. 
@93   gestfips     2. 
@96   gtcbsa       5. 
@101  gtco         3. 
@104  gtcbsast     1. 
@105  gtmetsta     1. 
@106  gtindvpc     1. 
@107  gtcbsasz     1. 
@108  gtcsa        3. 
@114  proldrrp     2. 
@116  pupelig      2. 
@118  perrp        2. 
@120  peparent     2. 
@122  prtage       2. 
@124  prtfage      1. 
@125  pemaritl     2. 
@127  pespouse     2. 
@129  pesex        2. 
@131  peafever     2. 
@135  peafnow      2. 
@137  peeduca      2. 
@139  ptdtrace     2. 
@141  prdthsp      2. 
@143  puchinhh     2. 
@147  pulineno     2. 
@151  prfamnum     2. 
@153  prfamrel     2. 
@155  prfamtyp     2. 
@157  pehspnon     2. 
@159  prmarsta     2. 
@161  prpertyp     2. 
@163  penatvty     3. 
@166  pemntvty     3. 
@169  pefntvty     3. 
@172  prcitshp     2. 
@174  prcitflg     2. 
@176  prinusyr     2. 
@178  puslfprx     2. 
@180  pemlr        2. 
@182  puwk         2. 
@184  pubus1       2. 
@186  pubus2ot     2. 
@188  pubusck1     2. 
@190  pubusck2     2. 
@192  pubusck3     2. 
@194  pubusck4     2. 
@196  puretot      2. 
@198  pudis        2. 
@200  peret1       2. 
@202  pudis1       2. 
@204  pudis2       2. 
@206  puabsot      2. 
@208  pulay        2. 
@210  peabsrsn     2. 
@212  peabspdo     2. 
@214  pemjot       2. 
@216  pemjnum      2. 
@218  pehrusl1     2. 
@220  pehrusl2     2. 
@222  pehrftpt     2. 
@224  pehruslt     3. 
@227  pehrwant     2. 
@229  pehrrsn1     2. 
@231  pehrrsn2     2. 
@233  pehrrsn3     2. 
@235  puhroff1     2. 
@237  puhroff2     2. 
@239  puhrot1      2. 
@241  puhrot2      2. 
@243  pehract1     2. 
@245  pehract2     2. 
@247  pehractt     3. 
@250  pehravl      2. 
@257  puhrck1      2. 
@259  puhrck2      2. 
@261  puhrck3      2. 
@263  puhrck4      2. 
@265  puhrck5      2. 
@267  puhrck6      2. 
@269  puhrck7      2. 
@271  puhrck12     2. 
@273  pulaydt      2. 
@275  pulay6m      2. 
@277  pelayavl     2. 
@279  pulayavr     2. 
@281  pelaylk      2. 
@283  pelaydur     3. 
@286  pelayfto     2. 
@288  pulayck1     2. 
@290  pulayck2     2. 
@292  pulayck3     2. 
@294  pulk         2. 
@296  pelkm1       2. 
@298  pulkm2       2. 
@300  pulkm3       2. 
@302  pulkm4       2. 
@304  pulkm5       2. 
@306  pulkm6       2. 
@308  pulkdk1      2. 
@310  pulkdk2      2. 
@312  pulkdk3      2. 
@314  pulkdk4      2. 
@316  pulkdk5      2. 
@318  pulkdk6      2. 
@320  pulkps1      2. 
@322  pulkps2      2. 
@324  pulkps3      2. 
@326  pulkps4      2. 
@328  pulkps5      2. 
@330  pulkps6      2. 
@332  pelkavl      2. 
@334  pulkavr      2. 
@336  pelkll1o     2. 
@338  pelkll2o     2. 
@340  pelklwo      2. 
@342  pelkdur      3. 
@345  pelkfto      2. 
@347  pedwwnto     2. 
@349  pedwrsn      2. 
@351  pedwlko      2. 
@353  pedwwk       2. 
@355  pedw4wk      2. 
@357  pedwlkwk     2. 
@359  pedwavl      2. 
@361  pedwavr      2. 
@363  pudwck1      2. 
@365  pudwck2      2. 
@367  pudwck3      2. 
@369  pudwck4      2. 
@371  pudwck5      2. 
@373  pejhwko      2. 
@375  pujhdp1o     2. 
@377  pejhrsn      2. 
@379  pejhwant     2. 
@381  pujhck1      2. 
@383  pujhck2      2. 
@385  prabsrea     2. 
@387  prcivlf      2. 
@389  prdisc       2. 
@391  premphrs     2. 
@393  prempnot     2. 
@395  prexplf      2. 
@397  prftlf       2. 
@399  prhrusl      2. 
@401  prjobsea     2. 
@403  prpthrs      2. 
@405  prptrea      2. 
@407  prunedur     3. 
@412  pruntype     2. 
@414  prwksch      2. 
@416  prwkstat     2. 
@418  prwntjob     2. 
@420  pujhck3      2. 
@422  pujhck4      2. 
@424  pujhck5      2. 
@426  puiodp1      2. 
@428  puiodp2      2. 
@430  puiodp3      2. 
@432  peio1cow     2. 
@434  puio1mfg     2. 
@442  peio2cow     2. 
@444  puio2mfg     2. 
@452  puiock1      2. 
@454  puiock2      2. 
@456  puiock3      2. 
@458  prioelg      2. 
@460  pragna       2. 
@462  prcow1       2. 
@464  prcow2       2. 
@466  prcowpg      2. 
@468  prdtcow1     2. 
@470  prdtcow2     2. 
@472  prdtind1     2. 
@474  prdtind2     2. 
@476  prdtocc1     2. 
@478  prdtocc2     2. 
@480  premp        2. 
@482  prmjind1     2. 
@484  prmjind2     2. 
@486  prmjocc1     2. 
@488  prmjocc2     2. 
@490  prmjocgr     2. 
@492  prnagpws     2. 
@494  prnagws      2. 
@496  prsjmj       2. 
@498  prerelg      2. 
@500  peernuot     2. 
@502  peernper     2. 
@504  peernrt      2. 
@506  peernhry     2. 
@508  puernh1c    4.2 
@512  peernh2     4.2 
@516  peernh1o    4.2 
@520  prernhly    4.2 
@524  pthr         1. 
@525  peernhro     2. 
@527  prernwa     8.2 
@535  ptwk         1. 
@540  peern       8.2 
@548  puern2      8.2 
@556  ptot         1. 
@559  peernwkp     2. 
@561  peernlab     2. 
@563  peerncov     2. 
@565  penlfjh      2. 
@567  penlfret     2. 
@569  penlfact     2. 
@571  punlfck1     2. 
@573  punlfck2     2. 
@575  peschenr     2. 
@577  peschft      2. 
@579  peschlvl     2. 
@581  prnlfsch     2. 
@583  pwfmwgt    10.4 
@593  pwlgwgt    10.4 
@603  pworwgt    10.4 
@613  pwsswgt    10.4 
@623  pwvetwgt   10.4 
@633  prchld       2. 
@635  prnmchld     2. 
@639  prwernal     2. 
@641  prhernal     2. 
@643  hxtenure     2. 
@645  hxhousut     2. 
@647  hxtelhhd     2. 
@649  hxtelavl     2. 
@651  hxphoneo     2. 
@653  pxinusyr     2. 
@655  pxrrp        2. 
@657  pxparent     2. 
@659  pxage        2. 
@661  pxmaritl     2. 
@663  pxspouse     2. 
@665  pxsex        2. 
@667  pxafwhn1     2. 
@669  pxafnow      2. 
@671  pxeduca      2. 
@673  pxrace1      2. 
@675  pxnatvty     2. 
@677  pxmntvty     2. 
@679  pxfntvty     2. 
@683  pxhspnon     2. 
@685  pxmlr        2. 
@687  pxret1       2. 
@689  pxabsrsn     2. 
@691  pxabspdo     2. 
@693  pxmjot       2. 
@695  pxmjnum      2. 
@697  pxhrusl1     2. 
@699  pxhrusl2     2. 
@701  pxhrftpt     2. 
@703  pxhruslt     2. 
@705  pxhrwant     2. 
@707  pxhrrsn1     2. 
@709  pxhrrsn2     2. 
@711  pxhract1     2. 
@713  pxhract2     2. 
@715  pxhractt     2. 
@717  pxhrrsn3     2. 
@719  pxhravl      2. 
@721  pxlayavl     2. 
@723  pxlaylk      2. 
@725  pxlaydur     2. 
@727  pxlayfto     2. 
@729  pxlkm1       2. 
@731  pxlkavl      2. 
@733  pxlkll1o     2. 
@735  pxlkll2o     2. 
@737  pxlklwo      2. 
@739  pxlkdur      2. 
@741  pxlkfto      2. 
@743  pxdwwnto     2. 
@745  pxdwrsn      2. 
@747  pxdwlko      2. 
@749  pxdwwk       2. 
@751  pxdw4wk      2. 
@753  pxdwlkwk     2. 
@755  pxdwavl      2. 
@757  pxdwavr      2. 
@759  pxjhwko      2. 
@761  pxjhrsn      2. 
@763  pxjhwant     2. 
@765  pxio1cow     2. 
@767  pxio1icd     2. 
@769  pxio1ocd     2. 
@771  pxio2cow     2. 
@773  pxio2icd     2. 
@775  pxio2ocd     2. 
@777  pxernuot     2. 
@779  pxernper     2. 
@781  pxernh1o     2. 
@783  pxernhro     2. 
@785  pxern        2. 
@791  pxernwkp     2. 
@793  pxernrt      2. 
@795  pxernhry     2. 
@797  pxernh2      2. 
@799  pxernlab     2. 
@801  pxerncov     2. 
@803  pxnlfjh      2. 
@805  pxnlfret     2. 
@807  pxnlfact     2. 
@809  pxschenr     2. 
@811  pxschft      2. 
@813  pxschlvl     2. 
@815  qstnum      $5. 
@820  occurnum    $2. 
@822  pedipged     2. 
@824  pehgcomp     2. 
@826  pecyc        2. 
@828  pegrprof     2. 
@830  pegr6cor     2. 
@832  pems123      2. 
@834  pxdipged     2. 
@836  pxhgcomp     2. 
@838  pxcyc        2. 
@840  pxgrprof     2. 
@842  pxgr6cor     2. 
@844  pxms123      2. 
@846  pwcmpwgt   10.4 
@856  peio1icd     4. 
@860  peio1ocd     4. 
@864  peio2icd     4. 
@868  peio2ocd     4. 
@872  primind1     2. 
@874  primind2     2. 
@876  peafwhn1     2. 
@878  peafwhn2     2. 
@880  peafwhn3     2. 
@882  peafwhn4     2. 
@884  pxafever     2. 
@886  pelndad      2. 
@888  pelnmom      2. 
@890  pedadtyp     2. 
@892  pemomtyp     2. 
@894  pecohab      2. 
@896  pxlndad      2. 
@898  pxlnmom      2. 
@900  pxdadtyp     2. 
@902  pxmomtyp     2. 
@904  pxcohab      2. 
@906  pedisear     2. 
@908  pediseye     2. 
@910  pedisrem     2. 
@912  pedisphy     2. 
@914  pedisdrs     2. 
@916  pedisout     2. 
@918  prdisflg     2. 
@920  pxdisear     2. 
@922  pxdiseye     2. 
@924  pxdisrem     2. 
@926  pxdisphy     2. 
@928  pxdisdrs     2. 
@930  pxdisout     2. 
@932  hxfaminc     2. 
@934  prdasian     2. 
;